# Generated by Django 5.2.11 on 2026-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_rename_student_name_to_file_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="essay",
            options={"ordering": ["file_name"]},
        ),
        migrations.AlterField(
            model_name="essay",
            name="file_name",
            field=models.CharField(
                help_text="Original filename of the uploaded essay", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="essay",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("graded", "Graded"),
                    ("reviewed", "Reviewed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
