# Generated by Django 5.2.11 on 2026-03-05 16:28

from django.db import migrations, models


def set_initial_review_state(apps, schema_editor):
    CriterionScore = apps.get_model("grading", "CriterionScore")

    for score in CriterionScore.objects.select_related("grading_result").all():
        if score.teacher_level_id is not None:
            score.teacher_review_state = "overridden"
            score.teacher_reviewed_at = score.grading_result.approved_at
        elif score.grading_result.teacher_approved:
            score.teacher_review_state = "accepted_ai"
            score.teacher_reviewed_at = score.grading_result.approved_at
        else:
            score.teacher_review_state = "pending"
            score.teacher_reviewed_at = None
        score.save(update_fields=["teacher_review_state", "teacher_reviewed_at"])


def unset_initial_review_state(apps, schema_editor):
    CriterionScore = apps.get_model("grading", "CriterionScore")
    CriterionScore.objects.update(
        teacher_review_state="pending",
        teacher_reviewed_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionscore',
            name='teacher_review_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_ai', 'Accepted AI'), ('overridden', 'Overridden')], default='pending', help_text='Teacher review disposition for this criterion', max_length=20),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='teacher_reviewed_at',
            field=models.DateTimeField(blank=True, help_text="When the teacher finalized this criterion's review state", null=True),
        ),
        migrations.RunPython(set_initial_review_state, unset_initial_review_state),
    ]
