/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all assignments owned by the authenticated user. */
        get: operations["assignments_assignment_list"];
        put?: never;
        /** @description Create a new assignment linked to a rubric. */
        post: operations["assignments_assignment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve an assignment with its nested essays. */
        get: operations["assignments_assignment_retrieve"];
        put?: never;
        post?: never;
        /** @description Delete an assignment and all its essays. */
        delete: operations["assignments_assignment_delete"];
        options?: never;
        head?: never;
        /** @description Partially update an assignment's title, prompt, source_text, or rubric. */
        patch: operations["assignments_assignment_partial_update"];
        trace?: never;
    };
    "/api/assignments/{assignment_id}/essays/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all essays in an assignment. */
        get: operations["assignments_essay_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}/export/csv/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Export assignment grades as a CSV file download. */
        get: operations["assignments_export_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}/export/pdf/{essay_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download an essay's original uploaded file. */
        get: operations["assignments_export_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload essay files to an assignment. Accepts individual PDF, DOCX, or TXT files, or a ZIP archive containing multiple files. Triggers async text extraction. */
        post: operations["assignments_essay_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Change the authenticated user's password. */
        post: operations["auth_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get or update current user profile. */
        get: operations["auth_me_retrieve"];
        /** @description Get or update current user profile. */
        put: operations["auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Get or update current user profile. */
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a new teacher account. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/{essay_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve an essay with its extracted text content. */
        get: operations["essays_essay_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/{essay_id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete an essay from its assignment. */
        delete: operations["essays_essay_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/{essay_id}/grading/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get grading result for an essay. Not yet implemented. */
        get: operations["essays_grading_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update grading result for an essay. Not yet implemented. */
        patch: operations["essays_grading_partial_update"];
        trace?: never;
    };
    "/api/essays/{essay_id}/grading/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve an AI grading result. Not yet implemented. */
        post: operations["essays_grading_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all rubrics owned by the authenticated user. */
        get: operations["rubrics_rubric_list"];
        put?: never;
        /** @description Create a new rubric. */
        post: operations["rubrics_rubric_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve a rubric with nested criteria and levels. */
        get: operations["rubrics_rubric_retrieve"];
        put?: never;
        post?: never;
        /** @description Delete a rubric. Fails if any assignment references it. */
        delete: operations["rubrics_rubric_delete"];
        options?: never;
        head?: never;
        /** @description Partially update a rubric's title or description. */
        patch: operations["rubrics_rubric_partial_update"];
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/criteria/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add a criterion to a rubric. */
        post: operations["rubrics_criterion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/criteria/{criterion_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a criterion and all its levels. */
        delete: operations["rubrics_criterion_delete"];
        options?: never;
        head?: never;
        /** @description Partially update a criterion's name or order. */
        patch: operations["rubrics_criterion_partial_update"];
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/criteria/{criterion_id}/levels/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add a scoring level to a criterion. */
        post: operations["rubrics_level_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/criteria/{criterion_id}/levels/{level_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a scoring level. */
        delete: operations["rubrics_level_delete"];
        options?: never;
        head?: never;
        /** @description Partially update a scoring level's score or descriptor. */
        patch: operations["rubrics_level_partial_update"];
        trace?: never;
    };
    "/api/rubrics/{rubric_id}/criteria/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reorder criteria within a rubric. Provide all criterion UUIDs in desired order. */
        post: operations["rubrics_criterion_reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for assignment details. */
        Assignment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            rubric: string;
            title: string;
            /** @description Writing assignment prompt for AI */
            prompt: string;
            /** @description Reference material for the essay */
            source_text?: string;
            readonly status: components["schemas"]["AssignmentStatusEnum"];
            readonly essays: components["schemas"]["EssayList"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer for assignment list. */
        AssignmentList: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            readonly status: components["schemas"]["AssignmentStatusEnum"];
            readonly essay_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `grading` - Grading
         *     * `review` - Review
         *     * `completed` - Completed
         * @enum {string}
         */
        AssignmentStatusEnum: "draft" | "grading" | "review" | "completed";
        AssignmentUploadRequest: {
            /** @description One or more files (PDF, DOCX, TXT) or a ZIP archive. */
            files: string[];
        };
        /** @description Serializer for password change. */
        ChangePassword: {
            old_password: string;
            new_password: string;
        };
        ChangePasswordSuccess: {
            /** @default Password changed successfully. */
            detail: string;
        };
        /** @description Serializer for criterion levels. */
        CriterionLevel: {
            /** Format: uuid */
            readonly id: string;
            /** Format: int64 */
            score: number;
            descriptor: string;
        };
        CriterionReorderRequest: {
            /** @description List of all criterion UUIDs in the desired order. */
            order: string[];
        };
        DetailResponse: {
            detail: string;
        };
        /** @description Serializer for essay details. */
        Essay: {
            /** Format: uuid */
            readonly id: string;
            /** @description Original filename of the uploaded essay */
            file_name: string;
            /** Format: uri */
            original_file: string;
            /** @description Converted text (via MarkItDown later) */
            readonly extracted_text: string;
            status?: components["schemas"]["EssayStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer for essay list (without extracted text). */
        EssayList: {
            /** Format: uuid */
            readonly id: string;
            /** @description Original filename of the uploaded essay */
            file_name: string;
            status?: components["schemas"]["EssayStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `processing` - Processing
         *     * `graded` - Graded
         *     * `reviewed` - Reviewed
         *     * `failed` - Failed
         * @enum {string}
         */
        EssayStatusEnum: "pending" | "processing" | "graded" | "reviewed" | "failed";
        /** @description Serializer for assignment details. */
        PatchedAssignment: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            rubric?: string;
            title?: string;
            /** @description Writing assignment prompt for AI */
            prompt?: string;
            /** @description Reference material for the essay */
            source_text?: string;
            readonly status?: components["schemas"]["AssignmentStatusEnum"];
            readonly essays?: components["schemas"]["EssayList"][];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for criterion levels. */
        PatchedCriterionLevel: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: int64 */
            score?: number;
            descriptor?: string;
        };
        /** @description Serializer for rubrics with nested criteria. */
        PatchedRubric: {
            /** Format: uuid */
            readonly id?: string;
            title?: string;
            description?: string;
            readonly criteria?: components["schemas"]["RubricCriterion"][];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for rubric criteria with nested levels. */
        PatchedRubricCriterion: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            /** Format: int64 */
            order?: number;
            readonly levels?: components["schemas"]["CriterionLevel"][];
        };
        /** @description Serializer for user profile. */
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            readonly email?: string;
            full_name?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for user registration. */
        Register: {
            /** Format: email */
            email: string;
            full_name?: string;
            password: string;
            password_confirm: string;
        };
        /** @description Serializer for rubrics with nested criteria. */
        Rubric: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string;
            readonly criteria: components["schemas"]["RubricCriterion"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer for rubric criteria with nested levels. */
        RubricCriterion: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: int64 */
            order?: number;
            readonly levels: components["schemas"]["CriterionLevel"][];
        };
        /** @description Serializer for rubric list (without nested criteria). */
        RubricList: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        UnauthorizedResponse: {
            /** @default Authentication credentials were not provided. */
            detail: string;
            /** @default not_authenticated */
            code: string;
        };
        /** @description Serializer for user profile. */
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            full_name?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ValidationErrorResponse: {
            /** @description Each field maps to a list of validation error strings. */
            field_name: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assignments_assignment_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentList"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    assignments_assignment_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Assignment"];
                "application/x-www-form-urlencoded": components["schemas"]["Assignment"];
                "multipart/form-data": components["schemas"]["Assignment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    assignments_assignment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_assignment_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_assignment_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAssignment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAssignment"];
                "multipart/form-data": components["schemas"]["PatchedAssignment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_essay_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EssayList"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_export_csv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_export_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    assignments_essay_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AssignmentUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EssayList"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordSuccess"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    essays_essay_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Essay"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    essays_essay_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    essays_grading_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    essays_grading_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    essays_grading_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                essay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_rubric_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricList"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    rubrics_rubric_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rubric"];
                "application/x-www-form-urlencoded": components["schemas"]["Rubric"];
                "multipart/form-data": components["schemas"]["Rubric"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    rubrics_rubric_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_rubric_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_rubric_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRubric"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRubric"];
                "multipart/form-data": components["schemas"]["PatchedRubric"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_criterion_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricCriterion"];
                "application/x-www-form-urlencoded": components["schemas"]["RubricCriterion"];
                "multipart/form-data": components["schemas"]["RubricCriterion"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricCriterion"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_criterion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_criterion_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRubricCriterion"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRubricCriterion"];
                "multipart/form-data": components["schemas"]["PatchedRubricCriterion"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricCriterion"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_level_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionLevel"];
                "application/x-www-form-urlencoded": components["schemas"]["CriterionLevel"];
                "multipart/form-data": components["schemas"]["CriterionLevel"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionLevel"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_level_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                level_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_level_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                level_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCriterionLevel"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCriterionLevel"];
                "multipart/form-data": components["schemas"]["PatchedCriterionLevel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionLevel"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    rubrics_criterion_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionReorderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CriterionReorderRequest"];
                "multipart/form-data": components["schemas"]["CriterionReorderRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
}
