# Generated by Django 5.2.11 on 2026-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_essay_status_add_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Active Celery task ID for grading', max_length=255),
        ),
    ]
