# Generated by Django 5.2.11 on 2026-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_add_failure_reason_to_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the last grading run finished.', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grading_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current grading run started.', null=True),
        ),
    ]
