# Generated by Django 5.2.11 on 2026-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0007_assignment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="grading_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the last grading run finished", null=True
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="grading_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the current grading run started", null=True
            ),
        ),
        migrations.AlterField(
            model_name="essay",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("graded", "Ready for Review"),
                    ("reviewed", "Reviewed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
