# Generated by Django 5.2.11 on 2026-03-03 18:24

import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_rubric_versioning_and_level_order(apps, schema_editor):
    Rubric = apps.get_model("rubrics", "Rubric")
    CriterionLevel = apps.get_model("rubrics", "CriterionLevel")

    for rubric in Rubric.objects.all().only("id"):
        rubric.family_id = rubric.id
        rubric.version = 1
        rubric.save(update_fields=["family_id", "version"])

    for level in CriterionLevel.objects.all().only("id", "score"):
        level.order = level.score
        level.save(update_fields=["order"])


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterionlevel',
            options={'ordering': ['order', 'score']},
        ),
        migrations.AddField(
            model_name='criterionlevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='family_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='rubric',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            backfill_rubric_versioning_and_level_order,
            reverse_code=reverse_noop,
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('user', 'family_id', 'version'), name='rubric_user_family_version_unique'),
        ),
    ]
