# Generated by Django 5.2.11 on 2026-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rubrics", "0002_alter_criterionlevel_options_criterionlevel_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rubric",
            name="rubric_user_family_version_unique",
        ),
        migrations.RemoveField(
            model_name="rubric",
            name="family_id",
        ),
        migrations.RemoveField(
            model_name="rubric",
            name="version",
        ),
    ]
