"""
Django settings for instagrader project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from datetime import timedelta
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-hs2av+xhy^!!56%cn!(s)_sw&xq)iqpx4$6c!e)2#fs3u)l5yc",
)

DEBUG = os.getenv("DEBUG", "1") == "1"

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "").split(",")
    if os.getenv("ALLOWED_HOSTS")
    else []
)

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular",
    "accounts",
    "rubrics",
    "assignments",
    "grading",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "instagrader.urls"

TEMPLATES = [  # type: ignore[reportUnknownVariableType]
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "instagrader.wsgi.application"

if os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.getenv("POSTGRES_HOST", "postgres"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

JWT_AUTH_COOKIE = "access_token"
JWT_AUTH_REFRESH_COOKIE = "refresh_token"
JWT_AUTH_SECURE = os.getenv("JWT_AUTH_SECURE", str(not DEBUG)).lower() in ("true", "1")
JWT_AUTH_SAMESITE = "Lax"

CORS_ALLOWED_ORIGINS = (
    os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if os.getenv("CORS_ALLOWED_ORIGINS")
    else ["http://localhost:3000"]
)
CORS_ALLOW_CREDENTIALS = True

SPECTACULAR_SETTINGS = {
    "TITLE": "InstaGrader API",
    "DESCRIPTION": "API for the InstaGrader essay grading platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [
        {"name": "auth", "description": "Authentication and user management"},
        {"name": "rubrics", "description": "Rubric CRUD and nested criteria/levels"},
        {"name": "assignments", "description": "Assignment CRUD, upload, and export"},
        {"name": "essays", "description": "Essay detail, delete, and grading"},
    ],
    "ENUM_NAME_OVERRIDES": {
        "AssignmentStatusEnum": "assignments.models.Assignment.Status",
        "EssayStatusEnum": "assignments.models.Essay.Status",
    },
}

CELERY_BROKER_URL = os.getenv("VALKEY_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("VALKEY_URL", "redis://localhost:6379/0")

# inference profile arn for on-demand, imported model arn for fine-tuned
BEDROCK = {
    "MODEL_ID": os.getenv(
        "BEDROCK_MODEL_ID",
        # "arn:aws:bedrock:us-east-1:187489282488:imported-model/p0z1dqy4m8jr",
        "arn:aws:bedrock:ca-central-1:187489282488:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0",
    ),
    "REGION": os.getenv("BEDROCK_REGION", "ca-central-1"),
    "MAX_COMPLETION_TOKENS": int(os.getenv("BEDROCK_MAX_COMPLETION_TOKENS", "4096")),
    "TEMPERATURE": float(os.getenv("BEDROCK_TEMPERATURE", "0.0")),
}
